const enLang = {
  0: 'Y.I.D.',
  1: 'About the forum',
  2: 'Program',
  3: 'About us',
  4: 'date of the forum 23.10 - 27.10',
  5: 'We are looking for the best',
  6: `The Participants of the «Y.I.D.» are enterprising, ambitious and open young people from various countries of the world. An inalienable attribute of each participant is leadership qualities, emotional intelligence, an ability to build communication and implemented projects in the field of students self-government. There are no limits to perfection that's why the International Forum «Y. I.D.» is aimed to unlock new potential of  students for further personal and professional development.`,
  7: 'apply',
  8: 'Why Y. I. D.?',
  9: 'Y. I. D.?',
  10: 'International forum «Y. I.D.» is a special kind of platform that offers unique advantages and opportunities for international communication and cooperation. The importance of the forum lies in the following: ',
  11: 'Diversity of cultures and outlooks',
  12: ' Global network of professional connections',
  13: 'Development of intercultural skills',
  14: 'Exchange of knowledge and best practices ',
  15: 'Solving global problems',
  16: 'What our members say',
  17: 'Evgenia Shibkova',
  18: '"Y.I.D."- this is more than a forum, this is a small life that we will always remember for its atmosphere and people. 4 months of fruitful preparation and work of all the organizers, a week with a rich program of educational and cultural events. Despite the worries, emotions and sleepless nights, this is one of the most exciting weeks for students. This was my first experience organizing such a large-scale event, but we, together with the organizing committee, did a great job.',
  19: 'Anna Paramonova',
  20: 'Last year I was the coordinator of the forum participants. These moments close to your heart will forever remain in your memory. First you correspond blindly with a person by mail, and in the end you see in his admiring eyes the desire to definitely return to Minsk again.',
  21: 'Yulia Kunakhovets',
  22: 'The forum gave me many new acquaintances, impressions and mutual subscriptions on Instagram. We still communicate with the guys, we follow the colossal growth in each other’s scientific and professional activities. I hope that this year our participants will have the same sparkling eyes!',
  23: 'Evgenia Cherkas',
  24: 'At the forum I was a participant and representative of BSU student organizations. "Y.I.D." amazingly changed my understanding of the scale of interaction and existing opportunities for exchanging experiences with students from other countries and universities. The cool atmosphere charged me with energy for the whole year!',
  25: 'Alexandra Demid',
  26: 'Forum "Y.I.D." - this is an opportunity to form not only ideas, but also friendship. I was a curator, so I paid special attention to the participants. I can say with confidence that in the process I managed to significantly expand my geographical list of friends and broaden my horizons.',
  27: 'Valentina Khmelevskaya',
  28: '"Y.I.D. - 2021” became a breath of fresh air for me in the cloudy October of last year. The forum gave me close friends among both the organizers and participants. "Y.I.D." - these are the warmest memories and some of the best days of my entire student life!',
  29: 'Ksenia Bazhenova',
  30: 'Forum "M.I.R." For me, this is a huge responsibility and the same immense emotions. Actively improving my abilities in the field of social networking was brightened up by conversations with guys from other countries about differences in self-government and learning in general. I will remember with a smile those seconds at the closing of the forum, when everyone present stood applauding and continuously shouted “thank you” to the organizing committee, and it was hard to stay on my feet from fatigue.',
  31: 'Who are we?',
  32: 'About the Student Council of BSU',
  33: 'The Student Council of BSU is a consolidating body of students self-government of BSU, which has a special structure, goals and tasks, including all existing organizations and students self-government bodies of BSU. It also represents the interests of BSU students at various levels.',
  34: 'Events which are organized and supported by the Student Council of BSU:',
  35: ' International Youth Forum «Y.I.D.»;',
  36: ' Student initiative forum;',
  37: ' Educational seminar for the press services of students self-government — Media School of the Student Council of BSU  ',
  38: 'The journey the Student Council has gone through is full of iconic events not only for the Belarusian students, but also for students from different countries.',
  39: '',
  40: 'About the VII International Forum «Y.I.D.: Youth. Integration. Development.» ',
  41: '«Y.I.D.: Youth. Integration. Development.» is an annual international youth forum organized by the Belarusian State University in Minsk. This platform allows you to combine efforts to achieve common goals and ideas. The first «Y.I.D.» Forum took place in 2016. Since then about 500 students from 23 countries of Europe and Asia have become its participants. The event is presented in a popular «workshop» format, which is an interactive tool for education and development.',
  42: ' А cultural program has been prepared for the forum where the participants would exchange experience in organizing effective work of networking among students self-government bodies. ',
  43: "Let's reach the top together! ",
  44: 'About the forum',
  45: 'Program',
  46: 'About us',
  47: 'Telegram',
  48: 'Instagman',
  49: 'Social network',
};
